### PR TITLE
Try fix memory leak by hunch

### LINKED ISSUE #174: Fix expansion memory leak
Screenshot 2024-10-23 at 19 16 36

### PR DESCRIPTION
**Pull request by alex216**
fix #174 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new function for resolving environment variables, enhancing the app's ability to handle variable lookups efficiently.

- **Bug Fixes**
	- Improved memory management in the variable extraction process to prevent memory leaks.

- **Refactor**
	- Simplified the logic in the existing variable trimming function by delegating environment variable resolution to the new function, improving code modularity.

### CODE REVIEW

**Review by rask24 — COMMENTED** [review]
Still memory leak would exists.

``` bash
❯ valgrind --leak-check=full ./minishell
==2134230== Memcheck, a memory error detector
==2134230== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2134230== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==2134230== Command: ./minishell
==2134230==
minishell$ export A="Hello World"
minishell$ echo $A
Hello World
minishell$ exit
exit
==2134230==
==2134230== HEAP SUMMARY:
==2134230==     in use at exit: 234,399 bytes in 454 blocks
==2134230==   total heap usage: 2,202 allocs, 1,748 frees, 477,946 bytes allocated
==2134230==
==2134230== 12 bytes in 1 blocks are definitely lost in loss record 17 of 98
==2134230==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2134230==    by 0x11A3CD: ft_strdup (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x1187DC: ft_xstrdup (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x115FC3: trim_expanded_variable (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x115DE2: split_by_ifs (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x115915: expand_variable_on_list (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x11566F: expand (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x1147C3: execute_command (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x1177CD: loop (in /home/asuke/clang/minishell/minishell)
==2134230==    by 0x112EB2: main (in /home/asuke/clang/minishell/minishell)
==2134230==
==2134230== LEAK SUMMARY:
==2134230==    definitely lost: 12 bytes in 1 blocks
==2134230==    indirectly lost: 0 bytes in 0 blocks
==2134230==      possibly lost: 0 bytes in 0 blocks
==2134230==    still reachable: 234,387 bytes in 453 blocks
==2134230==         suppressed: 0 bytes in 0 blocks
==2134230== Reachable blocks (those to which a pointer was found) are not shown.
==2134230== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2134230==
==2134230== For lists of detected and suppressed errors, rerun with: -s
==2134230== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

File: src/expansion/trim_expanded_variable.c [hunk 1]
```diff
@@ -17,10 +17,23 @@ static bool	is_identifier_char(char c)
...
+	char	*value;
+	char	*result;
+
+	if (!is_identifier(candidate_key))
+		return (ft_xstrdup(""));
+	value = lookup_value(candidate_key, env);
+	if (!value)
+		return (ft_xstrdup(""));
+	result = ft_xstrdup(value);
+	return (result);
```
Comment (rask24) [inline src/expansion/trim_expanded_variable.c:31]: Is is able to delete `result`.

``` suggestion
    return (ft_xstrdup(value));
```

**Review by rask24 — APPROVED** [review]
@alex216 LGTM ☕
